/**
 * frontend/src/utils/cityReport.js — printable monthly city report.
 *
 * Same house pattern as PriorityPage's work order: build a self-contained HTML
 * string, window.open a blank tab, document.write it, let it print itself.
 * A printed page is not themed, so this one is plain white with black text.
 */

import { SEVERITY_LABELS, WORK_ORDER_LABELS } from './constants'
import { fmtRon, fmtDate, fmtNum } from './format'

const esc = (v) =>
  String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

const num = (v) => (v === null || v === undefined ? '—' : fmtNum(v))

/**
 * @param {object}  opts
 * @param {object}  opts.stats      GET /stats payload
 * @param {object}  opts.ops        GET /analytics/ops payload
 * @param {string}  opts.city       signed-in operator's city (may be empty)
 * @param {string}  opts.monthLabel e.g. "July 2026"
 */
export function printCityReport({ stats, ops, city, monthLabel }) {
  const s = stats || {}
  const o = ops || {}
  const budget = o.budget || {}
  const openBySev = o.open_by_severity || {}
  const ordersByStatus = budget.orders_by_status || {}

  const total = s.total_detections || 0
  const sevRows = [1, 2, 3, 4, 5].map(sev => {
    const count = (s.severity_breakdown || []).find(r => r.severity === sev)?.count || 0
    return {
      sev,
      label: SEVERITY_LABELS[sev] || `S${sev}`,
      count,
      share: total > 0 ? `${((count / total) * 100).toFixed(1)}%` : '—',
      open: Number(openBySev[sev] ?? 0),
    }
  })

  const orderRows = Object.entries(ordersByStatus)
    .filter(([, n]) => Number(n) > 0)
    .map(([status, n]) => `${WORK_ORDER_LABELS[status] || status}: ${n}`)

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>RDDS — Road condition report</title>
<style>
  @page { margin: 18mm; }
  body { font-family:'Segoe UI',sans-serif; color:#000; background:#fff; margin:0; padding:26px 30px; }
  h1 { margin:0 0 4px; font-size:22px; }
  h2 { margin:24px 0 8px; font-size:13px; text-transform:uppercase; letter-spacing:.08em; border-bottom:1px solid #000; padding-bottom:4px; }
  .sub { margin:0; font-size:12px; color:#333; }
  table { width:100%; border-collapse:collapse; margin-top:4px; }
  th { text-align:left; font-size:10.5px; text-transform:uppercase; letter-spacing:.06em; padding:6px 8px; border-bottom:1px solid #000; }
  td { padding:6px 8px; border-bottom:1px solid #ddd; font-size:12px; }
  td.n, th.n { text-align:right; font-family:'Consolas',monospace; }
  .note { margin-top:10px; font-size:10.5px; color:#444; }
  .foot { margin-top:26px; padding-top:8px; border-top:1px solid #000; font-size:10.5px; color:#444; }
</style></head><body>
<h1>RDDS road condition report</h1>
<p class="sub">${esc(city || 'All cities')} · ${esc(monthLabel || '')}</p>

<h2>Headline totals</h2>
<table>
  <tr><td>Total detections</td><td class="n">${num(total)}</td></tr>
  <tr><td>Critical damage (S4 and S5)</td><td class="n">${num(s.critical_count)}</td></tr>
  <tr><td>Average severity</td><td class="n">${s.avg_severity ?? '—'}</td></tr>
  <tr><td>Repaired</td><td class="n">${num(s.fixed_count)}</td></tr>
  <tr><td>Last survey processed</td><td class="n">${esc(fmtDate(s.last_survey_date))}</td></tr>
</table>

<h2>Severity breakdown</h2>
<table>
  <thead><tr><th>Band</th><th>Meaning</th><th class="n">Detections</th><th class="n">Share</th><th class="n">Still open</th></tr></thead>
  <tbody>
${sevRows.map(r => `    <tr>
      <td>S${r.sev}</td>
      <td>${esc(r.label)}</td>
      <td class="n">${num(r.count)}</td>
      <td class="n">${r.share}</td>
      <td class="n">${num(r.open)}</td>
    </tr>`).join('\n')}
  </tbody>
</table>

<h2>Repair performance</h2>
<table>
  <tr><td>Average time to repair</td><td class="n">${o.avg_days_to_repair != null ? `${o.avg_days_to_repair} days` : 'no data yet'}</td></tr>
  <tr><td>Open sites</td><td class="n">${num(o.open_total)}</td></tr>
  <tr><td>Repaired</td><td class="n">${num(o.fixed_total)}</td></tr>
  <tr><td>Came back after repair</td><td class="n">${num(o.reopened_count)}</td></tr>
</table>

<h2>Budget</h2>
<table>
  <tr><td>Estimated for open work</td><td class="n">${esc(fmtRon(budget.estimated_open_ron))}</td></tr>
  <tr><td>Estimated overall</td><td class="n">${esc(fmtRon(budget.estimated_all_ron))}</td></tr>
  <tr><td>Actually spent</td><td class="n">${esc(fmtRon(budget.actual_spent_ron))}</td></tr>
  <tr><td>Work orders</td><td class="n">${orderRows.length ? esc(orderRows.join(' · ')) : 'none yet'}</td></tr>
</table>
<p class="note">Estimates come from the work orders your team created.</p>

<div class="foot">Generated by RDDS on ${esc(new Date().toLocaleString())}.</div>
<script>window.onload = () => window.print()</script>
</body></html>`

  const w = window.open('', '_blank')
  if (!w) return
  w.document.write(html)
  w.document.close()
}
